version: '3.7'

services:
  postgres:
    image: postgres:11.1
    container_name: ticket_checker_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ticket_checker
      - POSTGRES_USER=ticket-user
      - POSTGRES_PASSWORD=ticket-password